/**
 * THE COMPILER.
 *
 *   source/{primitives,semantic,scales,brand}.ts
 *        │  npm run generate  (npx tsx)
 *        ▼
 *   generated/
 *     tokens.css          — :root (light) + .dark
 *     variables.ts        — wfColorBrandPrimary = '--wf-color-brand-primary' …
 *     tailwind-tokens.cjs — the Tailwind color/radius/spacing map (var() refs)
 *     index.ts            — barrel: constants + source maps + brand capability
 *
 * generated/ is build output — never hand-edited.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { lightColors, darkColors } from '../src/source/semantic'
import { borderWidth, spacing, radius, typeScale, elevation, motion, iconSize } from '../src/source/scales'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../src/generated')
mkdirSync(OUT, { recursive: true })

const kebab = (input: string) => input.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const pascal = (input: string) =>
  input.replace(/(^|[-_])([a-z0-9])/g, (_match, _sep, char) => char.toUpperCase())

// ── colour vars from a semantic map ────────────────────────────────────────────
type ColorMap = Record<string, Record<string, string>>
function colorVars(map: ColorMap): [string, string][] {
  const vars: [string, string][] = []
  for (const group of Object.keys(map))
    for (const key of Object.keys(map[group]))
      vars.push([`--wf-color-${kebab(group)}-${kebab(key)}`, map[group][key]])
  return vars
}

// ── scalar vars (spacing / radius / type / elevation / motion) ─────────────────
function scaleVars(prefix: string, obj: Record<string, string>): [string, string][] {
  return Object.entries(obj).map(([key, value]) => [`--wf-${prefix}-${kebab(String(key))}`, value])
}

const lightVars = colorVars(lightColors as ColorMap)
const darkVars  = colorVars(darkColors as ColorMap)

const scalarVars: [string, string][] = [
  ...scaleVars('border-width', borderWidth as Record<string, string>),
  ...scaleVars('spacing', spacing as Record<string, string>),
  ...scaleVars('icon-size', iconSize as Record<string, string>),
  ...scaleVars('radius', radius as Record<string, string>),
  ...scaleVars('font-size', typeScale.size as Record<string, string>),
  ...scaleVars('font-weight', typeScale.weight as Record<string, string>),
  ...scaleVars('leading', typeScale.lineHeight as Record<string, string>),
  ...scaleVars('tracking', typeScale.letterSpacing as Record<string, string>),
  ...scaleVars('shadow', elevation as Record<string, string>),
  ...scaleVars('duration', motion.duration as Record<string, string>),
  ...scaleVars('ease', motion.easing as Record<string, string>),
  ['--wf-font-sans', typeScale.fontFamily.sans],
  ['--wf-font-mono', typeScale.fontFamily.mono],
]

// ── emit tokens.css ─────────────────────────────────────────────────────────────
const block = (sel: string, vars: [string, string][]) =>
  `${sel} {\n${vars.map(([name, value]) => `  ${name}: ${value};`).join('\n')}\n}\n`

let css = `/* GENERATED by scripts/generate.ts — do not edit by hand. */\n\n`
css += block(':root', [...lightVars, ...scalarVars])
css += '\n' + block('.dark', darkVars)
writeFileSync(resolve(OUT, 'tokens.css'), css)

// ── emit variables.ts (wf* constants → raw CSS var names) ──────────────────────
function constName(prefix: string, group: string, key: string) {
  return `wf${pascal(prefix)}${pascal(group)}${pascal(key)}`
}
let vars = `/* GENERATED — do not edit. Each constant is the bare CSS var name. */\n\n`
for (const group of Object.keys(lightColors)) {
  for (const key of Object.keys((lightColors as ColorMap)[group])) {
    vars += `export const ${constName('color', group, key)} = '--wf-color-${kebab(group)}-${kebab(key)}'\n`
  }
}
writeFileSync(resolve(OUT, 'variables.ts'), vars)

// ── emit tailwind-tokens.cjs (legible semantic utilities) ──────────────────────
const cssVar = (name: string) => `var(${name})`
const tw = {
  colors: {
    background: cssVar('--wf-color-background-default'),
    surface: {
      DEFAULT: cssVar('--wf-color-background-paper'),
      subtle:  cssVar('--wf-color-background-subtle'),
      inset:   cssVar('--wf-color-background-inset'),
      inverse: cssVar('--wf-color-background-inverse'),
      track:   cssVar('--wf-color-background-track'),
    },
    overlay: cssVar('--wf-color-background-overlay'),
    // foreground text scale — `text-primary` for reading content, `text-secondary`
    // for optional captions, `text-tertiary` for the faintest hints.
    primary:      cssVar('--wf-color-text-primary'),
    secondary:    cssVar('--wf-color-text-secondary'),
    tertiary:     cssVar('--wf-color-text-tertiary'),
    disabled:     cssVar('--wf-color-text-disabled'),
    inverse:      cssVar('--wf-color-text-inverse'),
    contrast:     cssVar('--wf-color-text-contrast'),
    link:         cssVar('--wf-color-text-link'),
    'link-hover': cssVar('--wf-color-text-link-hover'),
    border: {
      DEFAULT: cssVar('--wf-color-border-default'),
      subtle:  cssVar('--wf-color-border-subtle'),
      strong:  cssVar('--wf-color-border-strong'),
      focus:   cssVar('--wf-color-border-focus'),
      inverse: cssVar('--wf-color-border-inverse'),
    },
    ring: cssVar('--wf-color-border-focus'),
    brand: {
      DEFAULT:           cssVar('--wf-color-brand-primary'),
      hover:             cssVar('--wf-color-brand-primary-hover'),
      active:            cssVar('--wf-color-brand-primary-active'),
      subtle:            cssVar('--wf-color-brand-primary-subtle'),
      muted:             cssVar('--wf-color-brand-primary-muted'),
      contrast:          cssVar('--wf-color-brand-primary-contrast'),
      secondary:         cssVar('--wf-color-brand-secondary'),
      'secondary-hover': cssVar('--wf-color-brand-secondary-hover'),
    },
    success: {
      DEFAULT: cssVar('--wf-color-status-success-default'),
      subtle:  cssVar('--wf-color-status-success-subtle'),
      muted:   cssVar('--wf-color-status-success-muted'),
      fg:      cssVar('--wf-color-status-success-text'),
    },
    warning: {
      DEFAULT: cssVar('--wf-color-status-warning-default'),
      subtle:  cssVar('--wf-color-status-warning-subtle'),
      muted:   cssVar('--wf-color-status-warning-muted'),
      fg:      cssVar('--wf-color-status-warning-text'),
    },
    error: {
      DEFAULT: cssVar('--wf-color-status-error-default'),
      subtle:  cssVar('--wf-color-status-error-subtle'),
      muted:   cssVar('--wf-color-status-error-muted'),
      fg:      cssVar('--wf-color-status-error-text'),
    },
    info: {
      DEFAULT: cssVar('--wf-color-status-info-default'),
      subtle:  cssVar('--wf-color-status-info-subtle'),
      muted:   cssVar('--wf-color-status-info-muted'),
      fg:      cssVar('--wf-color-status-info-text'),
    },
  },
  borderWidth: Object.fromEntries(
    Object.keys(borderWidth).map((name) => [name, cssVar(`--wf-border-width-${kebab(name)}`)]),
  ),
  borderRadius: Object.fromEntries(
    Object.keys(radius).map((name) => [name, cssVar(`--wf-radius-${kebab(name)}`)]),
  ),
  // Flat borderColor map — MUST be flat (not nested under `border`), otherwise
  // Tailwind names the utilities `border-border-strong` and the `border-strong`
  // class never exists. No DEFAULT, so the bare `.border` stays width-only (the
  // base layer supplies the default color); `border-border` is provided explicitly.
  borderColor: {
    border:              cssVar('--wf-color-border-default'),
    subtle:              cssVar('--wf-color-border-subtle'),
    strong:              cssVar('--wf-color-border-strong'),
    focus:               cssVar('--wf-color-border-focus'),
    inverse:             cssVar('--wf-color-border-inverse'),
    brand:               cssVar('--wf-color-brand-primary'),
    success:             cssVar('--wf-color-status-success-default'),
    warning:             cssVar('--wf-color-status-warning-default'),
    error:               cssVar('--wf-color-status-error-default'),
    info:                cssVar('--wf-color-status-info-default'),
    transparent:         'transparent',
    current:             'currentColor',
    white:               '#ffffff',
    black:               '#000000',
  },
  // Only the NAMED spacing tokens become Tailwind utilities (p-card, gap-gutter,
  // my-section…). The numeric ramp is intentionally NOT mapped — doing so would
  // clobber Tailwind's default 4px scale and break every numeric utility
  // (size-4, p-4, gap-2…). The numeric ramp still ships as --wf-spacing-* CSS
  // vars for token-driven inline use and the Spacing reference page.
  spacing: Object.fromEntries(
    Object.keys(spacing)
      .filter((name) => Number.isNaN(Number(name)))
      .map((name) => [name, cssVar(`--wf-spacing-${kebab(String(name))}`)]),
  ),
  // Icon sizing — single-class `size-icon*` utilities (width + height). Merge
  // under Tailwind's `size` scale (theme.extend.size) so size-4/size-full survive.
  size: {
    'icon-sm': cssVar('--wf-icon-size-sm'),
    icon:      cssVar('--wf-icon-size-md'),
    'icon-lg': cssVar('--wf-icon-size-lg'),
  },
  boxShadow: Object.fromEntries(
    Object.keys(elevation).map((name) => [name, cssVar(`--wf-shadow-${kebab(name)}`)]),
  ),
  fontFamily: {
    sans: ['var(--wf-font-sans)'],
    mono: ['var(--wf-font-mono)'],
  },
  fontSize: Object.fromEntries(
    Object.keys(typeScale.size).map((name) => [name, cssVar(`--wf-font-size-${kebab(name)}`)]),
  ),
}
writeFileSync(
  resolve(OUT, 'tailwind-tokens.cjs'),
  `/* GENERATED — do not edit. */\nmodule.exports = ${JSON.stringify(tw, null, 2)}\n`,
)

// ── emit index.ts barrel ────────────────────────────────────────────────────────
let idx = `/* GENERATED — do not edit. */\n`
idx += `export * from './variables'\n`
idx += `export { lightColors, darkColors } from '../source/semantic'\n`
idx += `export { palette } from '../source/primitives'\n`
idx += `export { borderWidth, spacing, radius, typeScale, elevation, motion, iconSize } from '../source/scales'\n`
idx += `export { brandRamp, brandVars } from '../source/brand'\n`
idx += `export type { Ramp, Mode } from '../source/brand'\n`
idx += `export { themeVars } from '../source/theme'\n`
idx += `export type { ThemeOverride } from '../source/theme'\n`
writeFileSync(resolve(OUT, 'index.ts'), idx)

console.log(
  `✓ tokens generated — ${lightVars.length} colors × 2 modes, ${scalarVars.length} scalars`,
)
