import {
  Rocket, Palette, SwatchBook, Type, Ruler, Layers, Gauge, Accessibility, Boxes,
  MousePointerClick, Tag, CreditCard, FormInput, ListChecks, CircleDot, ToggleRight,
  SlidersHorizontal, AppWindow, ChevronsUpDown, MessageSquare, PanelRight, Menu as MenuIcon,
  Info, CircleUser, LoaderCircle, Table as TableIcon, Map, Minus, TextCursorInput, BellRing,
  LayoutGrid, ExternalLink, CircleDashed, Group,
  Search, GalleryHorizontalEnd, ListOrdered, Bell,
  Box as BoxIcon, Rows3, ToggleLeft, Expand, PanelTop, Shapes,
  Tags, Command as CommandIcon, CalendarDays, BarChart3, Sheet as SheetIcon, Code2,
} from 'lucide-react'
import type { NavItem } from '@windforge/ui'

export const navItems: NavItem[] = [
  {
    type: 'section',
    label: 'Design system',
    items: [
      { label: 'Overview', icon: <Rocket />, path: '/' },
      { label: 'Theming', icon: <SwatchBook />, path: '/theming' },
      { label: 'Composition', icon: <PanelTop />, path: '/composition' },
    ],
  },
  {
    type: 'section',
    label: 'Foundations',
    items: [
      {
        type: 'group', label: 'Design tokens', icon: <Palette />, defaultOpen: true,
        children: [
          { label: 'Color', icon: <Palette />, path: '/foundations/color' },
          { label: 'Typography', icon: <Type />, path: '/foundations/typography' },
          { label: 'Spacing', icon: <Ruler />, path: '/foundations/spacing' },
          { label: 'Radius & elevation', icon: <Layers />, path: '/foundations/radius' },
          { label: 'All tokens', icon: <SwatchBook />, path: '/foundations/tokens' },
        ],
      },
      { label: 'Iconography', icon: <Shapes />, path: '/foundations/iconography' },
      { label: 'Accessibility', icon: <Accessibility />, path: '/foundations/accessibility' },
    ],
  },
  { type: 'divider' },
  {
    type: 'section',
    label: 'Components',
    items: [
      { label: 'Box', icon: <BoxIcon />, path: '/components/box' },
      { label: 'Stack', icon: <Rows3 />, path: '/components/stack' },
      { label: 'Grid', icon: <LayoutGrid />, path: '/components/grid' },
      { label: 'Text', icon: <Type />, path: '/components/text' },
      { label: 'Link', icon: <ExternalLink />, path: '/components/link' },
      { label: 'Button', icon: <MousePointerClick />, path: '/components/button' },
      { label: 'Button group', icon: <Group />, path: '/components/button-group' },
      { label: 'Toggle button', icon: <ToggleLeft />, path: '/components/toggle-button' },
      { label: 'Badge', icon: <Tag />, path: '/components/badge' },
      { label: 'Chip', icon: <CircleDashed />, path: '/components/chip' },
      { label: 'Card', icon: <CreditCard />, path: '/components/card' },
      { label: 'Input', icon: <TextCursorInput />, path: '/components/input' },
      { label: 'Form', icon: <FormInput />, path: '/components/form' },
      { label: 'Select', icon: <ChevronsUpDown />, path: '/components/select' },
      { label: 'Autocomplete', icon: <Search />, path: '/components/autocomplete' },
      { label: 'Multi-select', icon: <Tags />, path: '/components/multi-select' },
      { label: 'Date picker', icon: <CalendarDays />, path: '/components/date-picker' },
      { label: 'Checkbox', icon: <ListChecks />, path: '/components/checkbox' },
      { label: 'Radio group', icon: <CircleDot />, path: '/components/radio' },
      { label: 'Switch', icon: <ToggleRight />, path: '/components/switch' },
      { label: 'Slider', icon: <SlidersHorizontal />, path: '/components/slider' },
      { label: 'Tabs', icon: <AppWindow />, path: '/components/tabs' },
      { label: 'Accordion', icon: <ChevronsUpDown />, path: '/components/accordion' },
      { label: 'Dialog', icon: <MessageSquare />, path: '/components/dialog' },
      { label: 'Modal', icon: <Expand />, path: '/components/modal' },
      { label: 'Sheet', icon: <PanelRight />, path: '/components/sheet' },
      { label: 'Popover', icon: <MessageSquare />, path: '/components/popover' },
      { label: 'Dropdown menu', icon: <MenuIcon />, path: '/components/dropdown-menu' },
      { label: 'Command', icon: <CommandIcon />, path: '/components/command' },
      { label: 'Tooltip', icon: <Info />, path: '/components/tooltip' },
      { label: 'Alert', icon: <BellRing />, path: '/components/alert' },
      { label: 'Toast', icon: <Bell />, path: '/components/toast' },
      { label: 'Pagination', icon: <GalleryHorizontalEnd />, path: '/components/pagination' },
      { label: 'Stepper', icon: <ListOrdered />, path: '/components/stepper' },
      { label: 'Avatar', icon: <CircleUser />, path: '/components/avatar' },
      { label: 'Progress', icon: <LoaderCircle />, path: '/components/progress' },
      { label: 'Skeleton', icon: <Boxes />, path: '/components/skeleton' },
      { label: 'Table', icon: <TableIcon />, path: '/components/table' },
      { label: 'Data table', icon: <SheetIcon />, path: '/components/data-table' },
      { label: 'Chart', icon: <BarChart3 />, path: '/components/chart' },
      { label: 'Breadcrumb', icon: <Map />, path: '/components/breadcrumb' },
      { label: 'Separator', icon: <Minus />, path: '/components/separator' },
      { label: 'Code block', icon: <Code2 />, path: '/components/code-block' },
      { label: 'Textarea', icon: <TextCursorInput />, path: '/components/textarea' },
      { label: 'AppShell', icon: <Gauge />, path: '/components/app-shell' },
      { label: 'AppBar', icon: <PanelTop />, path: '/components/app-bar' },
    ],
  },
]
